use super::*;

pub(super) fn project_path_from_env(
    workspace_root: &Path,
    env_name: &str,
    default: &str,
) -> PathBuf {
    let raw = env::var_os(env_name)
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from(default));
    if raw.is_absolute() {
        raw
    } else {
        workspace_root.join(raw)
    }
}

pub(crate) fn non_empty_env(name: &str) -> Option<String> {
    env::var(name)
        .ok()
        .map(|value| value.trim().to_owned())
        .filter(|value| !value.is_empty())
}

pub(crate) fn write_and_print_vortex_env(workspace_root: &Path) -> Result<()> {
    let config = VortexConfig::from_env(workspace_root)?;
    write_vortex_env_script(&config)?;
    print_env_usage(&config);
    Ok(())
}

pub(super) fn write_vortex_env_script(config: &VortexConfig) -> Result<()> {
    if let Some(parent) = config
        .env_file
        .parent()
        .filter(|parent| !parent.as_os_str().is_empty())
    {
        fs::create_dir_all(parent).map_err(|error| {
            format!(
                "failed to create Vortex env directory '{}': {error}",
                parent.display()
            )
        })?;
    }

    ensure_download_wrappers(config)?;
    let network_exports = vortex_network_env_exports(config);
    let path_export_prefix = vortex_path_export_prefix(config);
    let content = format!(
        "# Generated by `cargo vortex-env` / `cargo vortex-install`.\n\
         # Source this file when using Vortex tools manually from a shell.\n\
         export VORTEX_HOME={}\n\
         export VORTEX_BUILD_DIR={}\n\
         export VORTEX_TOOL_DIR={}\n\
         export VORTEX_PATH={}\n\
         export PKG_CONFIG_PATH={}:\"${{PKG_CONFIG_PATH:-}}\"\n\
         export LD_LIBRARY_PATH={}:\"${{LD_LIBRARY_PATH:-}}\"\n\
         export PATH={}:\"${{PATH:-}}\"\n\
         export MANDREL_FETCH_RETRIES={}\n\
         export MANDREL_VORTEX_TOOLCHAIN_MODE={}\n\
         {}",
        shell_quote_lossy(config.source_dir.as_os_str()),
        shell_quote_lossy(config.build_dir.as_os_str()),
        shell_quote_lossy(config.tool_dir.as_os_str()),
        shell_quote_lossy(config.install_dir().as_os_str()),
        shell_quote_lossy(config.pkg_config_dir().as_os_str()),
        shell_quote_lossy(config.lib_dir().as_os_str()),
        path_export_prefix,
        config.fetch_retries,
        shell_quote_lossy(OsStr::new(config.toolchain_mode.as_str())),
        network_exports
    );

    fs::write(&config.env_file, content).map_err(|error| {
        format!(
            "failed to write Vortex env script '{}': {error}",
            config.env_file.display()
        )
    })?;
    println!("Wrote Vortex env script: {}", config.env_file.display());
    Ok(())
}

pub(super) fn vortex_network_env_exports(config: &VortexConfig) -> String {
    match config.normalized_download_proxy_prefix() {
        Some(prefix) => format!(
            "export MANDREL_GITHUB_PROXY_PREFIX={}\n",
            shell_quote_lossy(OsStr::new(&prefix))
        ),
        None => String::new(),
    }
}

pub(super) fn vortex_path_export_prefix(config: &VortexConfig) -> String {
    let simx = shell_quote_lossy(config.simx_dir().as_os_str());
    let bin = shell_quote_lossy(config.bin_dir().as_os_str());
    let vortex_bins = format!("{simx}:{bin}");
    if config.download_proxy_prefix.is_some() {
        format!(
            "{}:{}",
            shell_quote_lossy(config.download_wrapper_dir().as_os_str()),
            vortex_bins
        )
    } else {
        vortex_bins
    }
}

pub(super) fn ensure_download_wrappers(config: &VortexConfig) -> Result<()> {
    if config.download_proxy_prefix.is_none() {
        return Ok(());
    }

    let wrapper_dir = config.download_wrapper_dir();
    fs::create_dir_all(&wrapper_dir).map_err(|error| {
        format!(
            "failed to create Vortex download wrapper directory '{}': {error}",
            wrapper_dir.display()
        )
    })?;

    let mut wrote_any = false;
    for program in ["wget", "curl"] {
        match find_program_on_path_excluding(program, &wrapper_dir) {
            Some(real_program) => {
                write_download_wrapper(&wrapper_dir, program, &real_program)?;
                wrote_any = true;
            }
            None => warn!(
                program,
                "download helper command not found while creating Vortex wrappers"
            ),
        }
    }

    if !wrote_any {
        warn!(
            wrapper_dir = %wrapper_dir.display(),
            "no wget/curl wrappers were generated; Vortex downloads may still be slow or fail"
        );
    }

    Ok(())
}

pub(super) fn find_program_on_path_excluding(
    program: &str,
    excluded_dir: &Path,
) -> Option<PathBuf> {
    let path = env::var_os("PATH")?;
    env::split_paths(&path)
        .map(|dir| dir.join(program))
        .find(|candidate| candidate.is_file() && !candidate.starts_with(excluded_dir))
}

pub(super) fn write_download_wrapper(
    wrapper_dir: &Path,
    program: &str,
    real_program: &Path,
) -> Result<()> {
    let wrapper_path = wrapper_dir.join(program);
    let content = download_wrapper_script(real_program);
    fs::write(&wrapper_path, content).map_err(|error| {
        format!(
            "failed to write Vortex download wrapper '{}': {error}",
            wrapper_path.display()
        )
    })?;
    make_executable(&wrapper_path)?;
    Ok(())
}

pub(super) fn download_wrapper_script(real_program: &Path) -> String {
    format!(
        "#!/usr/bin/env bash\n\
         set -euo pipefail\n\
         REAL={}\n\
         PREFIX=\"${{MANDREL_GITHUB_PROXY_PREFIX:-${{PROXY_PREFIX:-}}}}\"\n\
         if [[ -n \"$PREFIX\" && \"$PREFIX\" != */ ]]; then\n\
         \tPREFIX=\"$PREFIX/\"\n\
         fi\n\
         rewrite_arg() {{\n\
         \tlocal arg=\"$1\"\n\
         \tif [[ -n \"$PREFIX\" ]]; then\n\
         \t\tcase \"$arg\" in\n\
         \t\t\thttps://github.com/*|http://github.com/*|https://raw.githubusercontent.com/*|http://raw.githubusercontent.com/*|https://objects.githubusercontent.com/*|http://objects.githubusercontent.com/*|https://github-releases.githubusercontent.com/*|http://github-releases.githubusercontent.com/*)\n\
         \t\t\t\tprintf '%s%s' \"$PREFIX\" \"$arg\"\n\
         \t\t\t\treturn\n\
         \t\t\t\t;;\n\
         \t\tesac\n\
         \tfi\n\
         \tprintf '%s' \"$arg\"\n\
         }}\n\
         args=()\n\
         for arg in \"$@\"; do\n\
         \targs+=(\"$(rewrite_arg \"$arg\")\")\n\
         done\n\
         exec \"$REAL\" \"${{args[@]}}\"\n",
        shell_quote_lossy(real_program.as_os_str())
    )
}

pub(super) fn make_executable(path: &Path) -> Result<()> {
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut permissions = fs::metadata(path)
            .map_err(|error| format!("failed to stat '{}': {error}", path.display()))?
            .permissions();
        permissions.set_mode(0o755);
        fs::set_permissions(path, permissions)
            .map_err(|error| format!("failed to chmod '{}': {error}", path.display()))?;
    }
    Ok(())
}

pub(super) fn print_install_success(config: &VortexConfig) {
    println!("Vortex install completed.");
    println!("source:  {}", config.source_dir.display());
    println!("build:   {}", config.build_dir.display());
    println!("tools:   {}", config.tool_dir.display());
    println!("install: {}", config.install_dir().display());
    print_env_usage(config);
}

pub(super) fn print_env_usage(config: &VortexConfig) {
    println!("env:     {}", config.env_file.display());
    println!("manual shell usage: source {}", config.env_file.display());
    println!("cargo xtask Vortex commands inject this environment automatically.");
}

pub(crate) fn apply_vortex_env(command: &mut Command, config: &VortexConfig) -> Result<()> {
    command.env("VORTEX_HOME", &config.source_dir);
    command.env("VORTEX_BUILD_DIR", &config.build_dir);
    command.env("VORTEX_TOOL_DIR", &config.tool_dir);
    command.env("VORTEX_PATH", config.install_dir());
    command.env("MANDREL_FETCH_RETRIES", config.fetch_retries.to_string());
    if let Some(prefix) = config.normalized_download_proxy_prefix() {
        command.env("MANDREL_GITHUB_PROXY_PREFIX", prefix);
    }
    apply_github_proxy_git_env(command, config);
    prepend_env_path(command, "PKG_CONFIG_PATH", config.pkg_config_dir())?;
    prepend_env_paths(
        command,
        "LD_LIBRARY_PATH",
        [
            config.build_dir.join("sw/runtime"),
            config.install_dir().join("runtime/lib"),
            config.lib_dir(),
            config.tool_dir.join("llvm-vortex/lib"),
        ],
    )?;

    let mut path_entries = Vec::new();
    if config.download_proxy_prefix.is_some() {
        ensure_download_wrappers(config)?;
        path_entries.push(config.download_wrapper_dir());
    }
    path_entries.push(config.tool_dir.join("llvm-vortex/bin"));
    path_entries.push(config.bin_dir());
    prepend_env_paths(command, "PATH", path_entries)?;
    Ok(())
}

pub(super) fn apply_github_proxy_git_env(command: &mut Command, config: &VortexConfig) {
    let Some(base) = config.git_proxy_base() else {
        return;
    };

    command.env(
        "GIT_CONFIG_COUNT",
        GITHUB_REWRITE_PATTERNS.len().to_string(),
    );
    for (index, pattern) in GITHUB_REWRITE_PATTERNS.iter().enumerate() {
        command.env(
            format!("GIT_CONFIG_KEY_{index}"),
            format!("url.{base}.insteadOf"),
        );
        command.env(format!("GIT_CONFIG_VALUE_{index}"), *pattern);
    }
}

pub(super) fn prepend_env_path(command: &mut Command, key: &str, path: PathBuf) -> Result<()> {
    prepend_env_paths(command, key, [path])
}

pub(super) fn prepend_env_paths<I>(command: &mut Command, key: &str, paths: I) -> Result<()>
where
    I: IntoIterator<Item = PathBuf>,
{
    let mut env_paths: Vec<PathBuf> = paths.into_iter().collect();
    if let Some(existing) = env::var_os(key) {
        env_paths.extend(env::split_paths(&existing));
    }
    let joined = env::join_paths(env_paths).map_err(|error| {
        XtaskError::message(format!(
            "failed to build {key} for Vortex command environment: {error}"
        ))
    })?;
    command.env(key, joined);
    Ok(())
}

#[cfg(test)]
mod tests {
    use std::env;
    use std::fs;
    use std::path::Path;
    use std::process::Command as StdCommand;
    use std::time::{SystemTime, UNIX_EPOCH};

    use crate::Result;
    use crate::command::shell_quote_lossy;

    use super::{download_wrapper_script, make_executable, write_riscv_gcc_wrapper};

    #[test]
    fn download_wrapper_prefixes_vortex_github_asset_url() -> Result<()> {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map_err(|error| format!("system clock before UNIX_EPOCH: {error}"))?
            .as_nanos();
        let base = env::temp_dir().join(format!(
            "mandrel-xtask-download-wrapper-{}-{nanos}",
            std::process::id()
        ));
        let _ = fs::remove_dir_all(&base);
        fs::create_dir_all(&base).map_err(|error| {
            format!(
                "failed to create test directory '{}': {error}",
                base.display()
            )
        })?;

        let real_program = base.join("real-wget");
        let captured_args = base.join("args.txt");
        let real_script = format!(
            "#!/usr/bin/env bash\nset -euo pipefail\nprintf '%s\\n' \"$@\" > {}\n",
            shell_quote_lossy(captured_args.as_os_str())
        );
        fs::write(&real_program, real_script).map_err(|error| {
            format!(
                "failed to write fake wget '{}': {error}",
                real_program.display()
            )
        })?;
        make_executable(&real_program)?;

        let wrapper = base.join("wget");
        fs::write(&wrapper, download_wrapper_script(&real_program))
            .map_err(|error| format!("failed to write wrapper '{}': {error}", wrapper.display()))?;
        make_executable(&wrapper)?;

        let original = "https://github.com/vortexgpgpu/vortex-toolchain-prebuilt/raw/v3.0/pocl/ubuntu/focal/pocl.tar.bz2";
        let status = StdCommand::new(&wrapper)
            .env("MANDREL_GITHUB_PROXY_PREFIX", "https://gh-proxy.org")
            .arg(original)
            .status()
            .map_err(|error| format!("failed to run wrapper '{}': {error}", wrapper.display()))?;
        if !status.success() {
            return Err(format!("wrapper exited with status {status}").into());
        }

        let captured = fs::read_to_string(&captured_args).map_err(|error| {
            format!(
                "failed to read captured args '{}': {error}",
                captured_args.display()
            )
        })?;
        assert_eq!(
            captured.trim(),
            "https://gh-proxy.org/https://github.com/vortexgpgpu/vortex-toolchain-prebuilt/raw/v3.0/pocl/ubuntu/focal/pocl.tar.bz2"
        );

        let _ = fs::remove_dir_all(&base);
        Ok(())
    }

    #[test]
    fn download_wrapper_leaves_non_github_args_unchanged() {
        let script = download_wrapper_script(Path::new("/usr/bin/curl"));

        assert!(script.contains("https://github.com/*"));
        assert!(script.contains("https://raw.githubusercontent.com/*"));
        assert!(script.contains("printf '%s' \"$arg\""));
    }

    #[cfg(unix)]
    #[test]
    fn riscv_gcc_wrapper_replaces_existing_symlink_without_touching_target() -> Result<()> {
        use std::os::unix::fs::symlink;

        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map_err(|error| format!("system clock before UNIX_EPOCH: {error}"))?
            .as_nanos();
        let base = env::temp_dir().join(format!(
            "mandrel-xtask-riscv-wrapper-{}-{nanos}",
            std::process::id()
        ));
        let _ = fs::remove_dir_all(&base);
        fs::create_dir_all(&base).map_err(|error| {
            format!(
                "failed to create test directory '{}': {error}",
                base.display()
            )
        })?;

        let real_gcc = base.join("real-riscv64-unknown-elf-gcc");
        fs::write(&real_gcc, "#!/usr/bin/env bash\nexit 0\n").map_err(|error| {
            format!("failed to write fake gcc '{}': {error}", real_gcc.display())
        })?;
        make_executable(&real_gcc)?;

        let include_dir = base.join("include");
        fs::create_dir_all(&include_dir).map_err(|error| {
            format!(
                "failed to create include dir '{}': {error}",
                include_dir.display()
            )
        })?;

        let symlink_target = base.join("system-gcc-placeholder");
        fs::write(&symlink_target, "do not overwrite\n").map_err(|error| {
            format!(
                "failed to write symlink target '{}': {error}",
                symlink_target.display()
            )
        })?;

        let wrapper = base.join("bin/riscv64-unknown-elf-gcc");
        fs::create_dir_all(
            wrapper
                .parent()
                .ok_or_else(|| format!("wrapper path '{}' has no parent", wrapper.display()))?,
        )
        .map_err(|error| format!("failed to create wrapper parent: {error}"))?;
        symlink(&symlink_target, &wrapper).map_err(|error| {
            format!(
                "failed to create test symlink '{}' -> '{}': {error}",
                wrapper.display(),
                symlink_target.display()
            )
        })?;

        write_riscv_gcc_wrapper(&wrapper, &real_gcc, &include_dir)?;

        let metadata = fs::symlink_metadata(&wrapper)
            .map_err(|error| format!("failed to stat wrapper '{}': {error}", wrapper.display()))?;
        assert!(!metadata.file_type().is_symlink());
        let wrapper_content = fs::read_to_string(&wrapper)
            .map_err(|error| format!("failed to read wrapper '{}': {error}", wrapper.display()))?;
        assert!(wrapper_content.contains("-isystem"));
        assert_eq!(
            fs::read_to_string(&symlink_target).map_err(|error| {
                format!(
                    "failed to read symlink target '{}': {error}",
                    symlink_target.display()
                )
            })?,
            "do not overwrite\n"
        );

        let _ = fs::remove_dir_all(&base);
        Ok(())
    }
}
